[package]
name = "rust-8"
version = "0.1.0"
authors = ["Nicolai Sehrt <nicolai.sehrt@mni.thm.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.17.0"
rand = "0.7.3"
spin_sleep = "1.0.0"